import Skawe from './config.js';

/**
 * @summary A directory of icon keys and icon codes
 */
Skawe.utils.icons = {
  account: 'account_circle',
  person_add: 'person_add',
  lock_outline: 'lock_outline',
  shopping_cart: 'shopping_cart',
  arrow_forward: 'arrow_forward',
  menu: 'menu',
  search: 'search',
  fast_forward: 'fast_forward',
  accessibility: 'accessibility',
  snooze: 'snooze',
  subdirectory_arrow_right: 'subdirectory_arrow_right',
  update: 'update',
  all_inclusive: 'all_inclusive',
  account_balance_wallet: 'account_balance_wallet',
  camera_roll: 'camera_roll',
  cloud_queue: 'cloud_queue',
  details: 'details',
  dns: 'dns',
  layers: 'layers',
  public: 'public',
  storage: 'storage',
  data_usage: 'data_usage',
  dvr: 'dvr',
  security:'security',
  chat: 'chat',
  email: 'email',
  add: 'add',
  create_new_folder: 'create_new_folder',
  settings_backup_restore: 'settings_backup_restore',
  swap_horiz: 'swap_horiz',
  access_time: 'access_time',
  add_alert: 'add_alert',
  keyboard_arrow_up: 'keyboard_arrow_up',
  keyboard_arrow_down: 'keyboard_arrow_down',
};
